spring.application.name=ayurvedic-backend

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ayurvedic_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=QmFzZTY0RW5jb2RlU2VjcmV0S2V5RW5zdXJlU2VjdXJlMTIzNDU2Nzg5
app.jwt.expiration-ms=3600000

# Security
spring.security.user.name=admin
spring.security.user.password=admin
